### ISSUE TITLE
Compile error on raspberry pi 5

### ISSUE THREAD

**Issue by perise** [nvpro-samples/vk_minimal_latest#2]
This vk_enum_string_helper.h helper file come after Vulkan 1.3.268.0 SDK, but on Raspberry Pi, the default SDK is still Version: 1.3.239
====
src/minimal_latest.cpp:136:10: fatal error: vulkan/vk_enum_string_helper.h: No such file or directory
  136 | #include "vulkan/vk_enum_string_helper.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by mklefrancois** [comment]
Thank you for reporting this, but as this project is aiming the very latest of Vulkan, and soon 1.4, many other functions and enum won't be supported. Maybe the best would be to file an issue to get Vulkan 1.4 on Raspberry Pi.
